### ISSUE TITLE
Safari浏览器下抓取pdf失败

### ISSUE THREAD

**Issue by mingga99** [l0o0/jasminum#87]
macos，茉莉花配置中更新了翻译器，浏览器中手动点击了update，cnki文章页面可以识别，但是无法抓取pdf，是什么原因
<img width="395" alt="截屏2022-04-19 下午11 46 47" src="https://user-images.githubusercontent.com/51311855/164065371-423abc02-f1a3-4f7d-9e16-c452de67f8f2.png">

**Comment by FR14NDS** [comment]
我也是，safari安装步骤来更新了浏览器内的translator，结果还是不行，同样的步骤google却可以

**Comment by f-reeeeee** [comment]
Mac air m1  也是这个问题，和楼上fri4nds一样。 我系统是vent 13点几    用mac上的edge connector 保存 最开始会崩，查教程更新translator过后就好了，嘎嘎快。    safari就是咋都不行。

**Comment by f-reeeeee** [comment]
> 我也是，safari安装步骤来更新了浏览器内的translator，结果还是不行，同样的步骤google却可以

现在有找到解决办法嘛

**Comment by pencilheart** [comment]
[zotero官方解释](https://forums.zotero.org/discussion/102365/zotero-connector-does-not-download-pdf-on-safari-but-does-on-chrome)

Unfortunately due to limitations of Safari saving resources behind paywalls, particularly PDFs cannot work as well as it does on Chrome, Firefox or Edge. You can either download those PDFs manually and attach them to saved items or use Chrome.
